[shell]
program = "/bin/zsh"

[window]
startup_mode = "Fullscreen"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 14

[mouse]
hide_when_typing = true
